#pragma config(Sensor, S3, HTIRS2, sensorI2CCustom)
#pragma config(Sensor, S2,     ,               sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     ,               sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "include/hitechnic-compass.h"
#include "include/hitechnic-irseeker-v2.h"

tHTMC compass;
tHTIRS2 irSeeker;

void OmniDrive(int side, int frontback, int turn){
	setMotorSpeed(motorC, (frontback - side) + turn);
	setMotorSpeed(motorB, ((frontback - side) - turn) - frontback);
	setMotorSpeed(motorA, -1 * (frontback + side) - turn);
}

int FrontCalibrate(){
	readSensor(&compass);
	string s = compass.relativeHeading;
	if(atoi(s) + 43 == 1 || atoi(s) + 43 == -1){
		return 0;
	}
	return atoi(s) + 43;
}

task main()
{
	initSensor(&irSeeker, S3);
	initSensor(&compass, S1);
	compass.offset = compass.heading;
	while(true){
		displayTextLine(2, "%4d", FrontCalibrate());
	}
}
